### ISSUE TITLE
When I copy a build, sometimes cornered stairs revert back to normal stairs

### ISSUE THREAD

**Issue by craftyfoxe** [SBPrime/AsyncWorldEdit#277]
When I copy and paste a build, the cornered stairs sometimes reverts back to normal stairs. You can see it in this video the top stairs turned. I'm using AsyncWorldEdit-3.6.15.jar and worldedit-bukkit-7.1.0-beta-1.jar
[https://streamable.com/65sze](https://streamable.com/65sze)

**Comment by SBPrime** [comment]
Did you disable physics freeze?

**Comment by craftyfoxe** [comment]
physicsFreeze is enabled

**Comment by SBPrime** [comment]
And what about the black list for physics freeze? 
The default should look like this:
```  physicsFreeze:                                                                                                     
    #Disable or enable blocks physics freeze when placing blocks                                                     
    enabled: true                                                                                                    
    #List of block for witch the physics freeze will be disabled                                                     
    blackList:                                                                                                       
    - "minecraft:acacia_stairs"                                                                                      
    - "minecraft:andesite_stairs"                                                                                    
    - "minecraft:birch_stairs"                                                                                       
    - "minecraft:brick_stairs"                                                                                       
    - "minecraft:cobblestone_stairs"                                                                                 
    - "minecraft:dark_oak_stairs"
    - "minecraft:dark_prismarine_stairs"
    - "minecraft:diorite_stairs"
    - "minecraft:end_stone_brick_stairs"
    - "minecraft:granite_stairs"
    - "minecraft:jungle_stairs"
    - "minecraft:mossy_stone_brick_stairs"
    - "minecraft:nether_brick_stairs"
    - "minecraft:oak_stairs"
    - "minecraft:polished_andesite_stairs"
    - "minecraft:polished_diorite_stairs"
    - "minecraft:polished_granite_stairs"
    - "minecraft:prismarine_brick_stairs"
    - "minecraft:prismarine_stairs"
    - "minecraft:purpur_stairs"
    - "minecraft:quartz_stairs"
    - "minecraft:red_nether_brick_stairs"
    - "minecraft:red_sandstone_stairs"
    - "minecraft:sandstone_stairs"
    - "minecraft:smooth_quartz_stairs"
    - "minecraft:smooth_red_sandstone_stairs"
    - "minecraft:smooth_sandstone_stairs"
    - "minecraft:spruce_stairs"
    - "minecraft:stone_brick_stairs"
    - "minecraft:stone_stairs"
```

**Comment by craftyfoxe** [comment]
Yes but my config doesn't have those quotation marks
```
  physicsFreeze:
    enabled: true
    blackList:
    - minecraft:acacia_stairs
    - minecraft:andesite_stairs
    - minecraft:birch_stairs
    - minecraft:brick_stairs
    - minecraft:cobblestone_stairs
    - minecraft:dark_oak_stairs
    - minecraft:dark_prismarine_stairs
    - minecraft:diorite_stairs
    - minecraft:end_stone_brick_stairs
    - minecraft:granite_stairs
    - minecraft:jungle_stairs
    - minecraft:mossy_stone_brick_stairs
    - minecraft:nether_brick_stairs
    - minecraft:oak_stairs
    - minecraft:polished_andesite_stairs
    - minecraft:polished_diorite_stairs
    - minecraft:polished_granite_stairs
    - minecraft:prismarine_brick_stairs
    - minecraft:prismarine_stairs
    - minecraft:purpur_stairs
    - minecraft:quartz_stairs
    - minecraft:red_nether_brick_stairs
    - minecraft:red_sandstone_stairs
    - minecraft:sandstone_stairs
    - minecraft:smooth_quartz_stairs
    - minecraft:smooth_red_sandstone_stairs
    - minecraft:smooth_sandstone_stairs
    - minecraft:spruce_stairs
    - minecraft:stone_brick_stairs
    - minecraft:stone_stairs
```
In any case I replace it with that and it still didn't work either way
