### ISSUE TITLE
Spamming CONSOLE

### ISSUE THREAD

**Issue by AeroSpace8** [SBPrime/AsyncWorldEdit#395]
Hey so the plugin keeps spamming my CONSOLE with `[01:41:15] [AWE:Cron:undoCleanup/INFO]: [AsyncWorldEdit] Undo cleanup started...
[01:41:15] [AWE:Cron:undoCleanup/INFO]: [AsyncWorldEdit] ...undo cleanup done.`

**Comment by AeroSpace8** [comment]
How can I disable that?

**Comment by x1p** [comment]
```yaml
awe:
  messages:
    undoCleanup: off
```
