### ISSUE TITLE
AWE does not load queue or stops during large edits

### ISSUE THREAD

**Issue by Noket** [SBPrime/AsyncWorldEdit#87]
EDIT: Updated config to fix these problems.

While editing more than 50 million blocks (just a rough guesstimate), AWE rarely queues up the blocks. When it does manage to queue the blocks, it stops working after changing a few hundred thousand or so.

Why does this happen, and how can we fix it (to be able to edit hundreds of millions of blocks) to not freeze?

**Server Startup**
22.02 21:01:13 [Server] INFO New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
22.02 21:01:13 [Server] INFO BlocksHub plugin not found.
22.02 21:01:13 [Server] INFO BarAPI not found.
22.02 21:01:13 [Server] INFO Error loading strings file, using internal fallback.
22.02 21:01:13 [Server] INFO Enabling AsyncWorldEdit v2.1.1

**Config**:
```yaml
awe:
  #Do not change
  version: 3
  rendering:
    #amount of time (in ticks) the server will place a chunk of blocks
    interval: 1
    #how often that a user will get an update on the current que (number of intervals)
    talk-interval: 20
    #maximum size of the blocks queue
    queue-max-size: 2147483645
  dispatcher:
    #(noket) The dispatcher runs in the background
    #and processes jobs that the player has exceeded...
    #maximum number of jobs performed in one runn
    #(nok) Max number of jobs the background proccessor does at once
    max-jobs: 6
    #maximum number of idle runs befor disabling dispatcher
    #How many sets of max-jobs jobs AWE will handle before disabling
    max-idle-runs: 2147483645
    #maximum number of miliseconds the dispatcher can use
    #This value should by lover then 50% o 1tick (25ms)
    max-time: 10
  #check for updates
  checkVersion: true
  #Disable or enable blocks physics freeze when placing blocks
  physicsFreez: true
  #Enable PlotMe Global Mask Fix
  plotMeFixEnabled: false
  #File containing all the messages
  strings: "english.yml"
  #Show debug messages
  debug: true
  #Blocks hub plugin options  
  blocksHub:
    #Enable block chang loggin
    logBlocks: false
    #Enable blocks access control
    checkAccess: false
  #Player permission groups.
  #Permission node: AWE.Groups.<group name>  
  permissionGroups:
    #The group entry (at least one group is required!)
    #If a player has multiple groups, the las one defined in the config
    #is assigned.
    default:
      #Indicates that the group is default.
      #Only one group can by default, if multiple groups are set to default
      #the first one is used asdefault. The default group is used for players
      #that do not have any other permission groups.
      isDefault: true
      #Maximum number of jobs a player can have. -1 --> no job limit
      maxJobs: 2
      #Enable or disable auto job cancelation on player quit
      cleanOnLogout: false
      #Default AWE status for loging in players 
      defaultMode: on
      renderer:
        #blocks to place (per-interval), this determines the max speed of block placing
        #if you experience lag lower this and the next number, use -1 for no limit
        blocks: -1
        #Maximum number of miliseconds spend on placing blocks, use -1 for no limit
        time: -1
      queue:
        #maximum size of the player block queue
        limit-hard: 2147483645
        #number of blocks on the player queue when to stop placing blocks
        limit-soft: 2147483645
      messages:
        #Whether or not to show progress using BarAPI
        progress-bar: false
        #Whether or not to show progress using the chat messages
        progress-chat: true
        #is async world edit talkative 
        talkative: true
#Example of additional vip group:
#    vip:
#      #you can remove this, the isDefault is by default set to false
#      isDefault: false 
#      maxJobs: -1
#      cleanOnLogout: false
#      #You can omit entries with that are same value as in the default group
#      #defaultMode: on
#      renderer:
#        blocks: 20000
#        time: -1
  #AWE will make the following WorldEdit actions async
  enabledOperations:
    - undo
    - redo
    - fillXZ
    - removeAbove
    - removeBelow
    - removeNear
    - setBlocks
    - replaceBlocks
    - makeCuboidFaces
    - makeCuboidWalls
    - overlayCuboidBlocks
    - naturalizeCuboidBlocks
    - stackCuboidRegion
    - moveCuboidRegion
    - drainArea
    - fixLiquid
    - makeCylinder
    - makeSphere
    - makePyramid
    - thaw
    - simulateSnow
    - green
    - makePumpkinPatches
    - makeForest
    - makeShape
    - deformRegion
    - hollowOutRegion
    - paste
    - copy
    - cut
    - regenerate
    - center
    - drawLine
    - drawSpline
    - makeBiomeShape
    - forest
    - flora
    - setBiome
    - loadSchematic
    - saveSchematic
    - craftScript
    - makeFaces
    - makeWalls
    - overlayBlocks
    - naturalizeBlocks
    - stackRegion
    - moveRegion
```
